defaults:
  - data: 64x128
  - model: sfno
  - training: train_default
  - paths: cluster
  - globals
  - _self_

wandb_entity: inverse-medical-imaging
wandb_project: neurop
accelerator: cpu
strategy: auto
devices: 1
batch_size: 16
precision: 32
debug: False
debug_batches: 10
num_sanity_val_steps: 1
log_every_n_steps: 1
num_workers: 4